name: Deploy Slides
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Her opgraderer vi fra 18 til 20 for at fixe fejlen
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install and Build
        run: |
          cd "slidev"
          npm install
          npm run build -- --base /DLE/
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./slidev/dist